name: RespawnChest
main: de.mahagst.risingworld.respawnchest.RespawnChestPlugin
version: 1.1.0
author: mahagst
description: Refill chests after loot with RESET templates
website: https://github.com/HaggerShose/rw-respawn-chest/releases/latest
